name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        
      - name: Build
        run: make build

      # - name: Archive
      #   run: tar -czvf bin.tar.gz bin/

      # - name: Upload Binaries
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: bin.tar.gz
      #     path: bin.tar.gz
