name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Test
        run: make ci-testing

      - name: Archive
        run: tar -czvf coverage.tar.gz coverage/

      # - name: Upload Coverage Info
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage.tar.gz
      #     path: coverage.tar.gz
